version: "3.5"
services: 
  backend:
    container_name: backend_1
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 81:3333
    volumes: 
      - ${PWD}/backend:/opt/ui
    command: yarn dev
  frontend:
    container_name: frontend_1
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes: 
      - ${PWD}/web:/opt/ui
    command: yarn start
  expo:
    container_name: expo-android_1
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports: 
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
    volumes:
      - ${PWD}/mobile:/opt/ui
    command: yarn start